version: '3.7'

services:
  app:
    image: kombustor/rss-fulltext-proxy:latest
    container_name: rssproxy
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis
    ports:
      - 3000:3000
    networks:
      - default
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=rssproxy"
      - "traefik.docker.network=web"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:rssproxy.yourdomain.tld"

  redis:
    image: redis:alpine
    container_name: rssproxy-redis
    restart: unless-stopped
    networks:
      - default

networks:
  web:
    external: true